### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by wujastyk** [catsmith/collation_editor#2]
My linux system, JRE, firefox, python versions are all as required.

- I installed. All good.  
- Ran startup.sh and connected with the localhost.  Good.
- There's CollateX.  Great!

Ran the first example, and got the error message

> XML Parsing Error: no element found Location: http://localhost:7369/collate Line Number 1, Column 1:

See screenshot.  It's apparently mostly working, but the Variant graph isn't appearing.

![screenshot from 2016-03-05 22 26 03](https://cloud.githubusercontent.com/assets/762246/13552670/869a7e10-e321-11e5-85c4-c0ae81127432.png)

**Comment by catsmith** [comment]
This is actually not a problem with the collation_editor itself but with the dependencies for a feature of the collateX demonstration not used by the collation_editor software. However, if you wish to get this feature of collateX working, then I think installing graphviz will fix it. Details under point 4 and 5 here
https://github.com/djbpitt/collatexInstallation/blob/master/collatex-installation.md.

**Comment by wujastyk** [comment]
Thanks! That got me going.  All good now.

Best,
Dominik
​
